---
- name: install rpms
  yum: name={{ item }} state=present
  with_items: rpm_packages

- name: yum update
  yum: name=* state=latest

- name: install packages from yum
  yum: name={{ item }} state=present
  with_items: yum_packages

- name: install server packages from yum
  yum: name={{ item }} state=present
  with_items: server_packages
