---
- name: install web packages from yum
  yum: name={{ item }} state=present enablerepo=mysql56-community,remi
  with_items: web_packages

- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: services
